"""Initial migration

Revision ID: d83f381a8fcf
Revises: 
Create Date: 2023-10-18 21:15:58.088238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd83f381a8fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('colegiatura', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.NCHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.alter_column('contraseña',
               existing_type=sa.VARCHAR(length=250, collation='Modern_Spanish_CI_AS'),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=250, collation='Modern_Spanish_CI_AS'),
               nullable=True)
        batch_op.alter_column('usuario',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               nullable=True)

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('colegiatura', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=10),
               type_=sa.NCHAR(length=10),
               existing_nullable=True)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61C8005343')
    )
    # ### end Alembic commands ###
